### ISSUE TITLE
Adicionar Restrições

### ISSUE THREAD

**Issue by DtKimura** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t9-pmv-ads-2024-1-e2-proj-barberease#10]
O desenvolvimento do sistema deverá ser desenvolvido apenas utilizando as linguagens e ferramentas: C#, HTML, CSS, JS, MySQL, Bootstrap e Visual Studio Code.

**Comment by willy-r** [comment]
Restrições adicionadas:

![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t9-pmv-ads-2024-1-e2-proj-barberease/assets/47596121/cbabe599-c083-44ea-bd61-0c27ad549c3f)
