### ISSUE TITLE
Revisar Restrição ID 02 - Não pode ser desenvolvido um módulo backend

### ISSUE THREAD

**Issue by DtKimura** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t9-pmv-ads-2024-1-e2-proj-barberease#11]
Esta restrição gerou dúvidas. Na verdade, deve ser desenvolvido um backend.

**Comment by willy-r** [comment]
Esse item veio padrão no template do projeto, já alterado em #10.
