### ISSUE TITLE
Desenvolver diagrama de caso de uso

### ISSUE THREAD

**Issue by DtKimura** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t9-pmv-ads-2024-1-e2-proj-barberease#4]
2º entrega de artefatos - 07/03/2024

**Comment by willy-r** [comment]
![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t9-pmv-ads-2024-1-e2-proj-barberease/assets/47596121/8c32605b-948e-4add-881a-4433164b1867)
