### ISSUE TITLE
Aprimorar requisitos funcionais e não funcionais

### ISSUE THREAD

**Issue by DtKimura** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t9-pmv-ads-2024-1-e2-proj-barberease#5]
2º entrega de artefatos - 07/03/2024

**Comment by DtKimura** [comment]
2º Entrega de artefatos - 07/03/2024

**Comment by willy-r** [comment]
Dei uma aprimorada nos requisitos, faltando apenas as **Restrições** do projeto e possíveis correções ou adições de mais histórias e requisitos de usuários.
