### ISSUE TITLE
Revisar diagrama de caso de uso

### ISSUE THREAD

**Issue by DtKimura** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t9-pmv-ads-2024-1-e2-proj-barberease#8]
Houve dúvida sobre a relação de herança entre o ator ADM e ator Cliente.

**Comment by willy-r** [comment]
Diagrama alterado para o seguinte, isso facilitará melhor o entendimento do sistema:

![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t9-pmv-ads-2024-1-e2-proj-barberease/assets/47596121/bc848aa5-db5b-41c2-be50-0a716be6161d)
