### ISSUE TITLE
Revisar RNF-003

### ISSUE THREAD

**Issue by DtKimura** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t9-pmv-ads-2024-1-e2-proj-barberease#9]
Houve dúvida a respeito do termo "alto tempo de atividade" na descrição do referido requisito não funcional. "A aplicação deve ter um alto tempo de atividade para que os usuários possam acessá-la sempre que precisarem"

**Comment by willy-r** [comment]
Refatorado para melhor entendimento:

![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t9-pmv-ads-2024-1-e2-proj-barberease/assets/47596121/cfa5a8bf-498f-4dfa-974d-8dd6b632b58a)
